[project]
name = "walmart-sales"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.10.9",
    "dbt-postgres>=1.9.0",
    "pandas>=2.3.1",
    "psycopg2-binary>=2.9.10",
]
