services:
  testdb:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - "5433:5432"
    volumes:
      - testdb_data:/var/lib/postgresql/data
    restart: unless-stopped
  
volumes:
  testdb_data: